### ISSUE TITLE
jmespath does not work if json key has a dash in the name

### ISSUE THREAD

**Issue by danielpops** [jmespath/jmespath.py#109]
Observe:

```
>>> d = {'a': 'b', 'a-b': 'b-c'}
>>> jmespath.search('a', d)
'b'
>>> jmespath.search('a-b', d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dpopes/scratch/python/virtualenv_run/lib/python2.7/site-packages/jmespath/__init__.py", line 12, in search
    return parser.Parser().parse(expression).search(data, options=options)
  File "/Users/dpopes/scratch/python/virtualenv_run/lib/python2.7/site-packages/jmespath/parser.py", line 87, in parse
    parsed_result = self._do_parse(expression)
  File "/Users/dpopes/scratch/python/virtualenv_run/lib/python2.7/site-packages/jmespath/parser.py", line 95, in _do_parse
    return self._parse(expression)
  File "/Users/dpopes/scratch/python/virtualenv_run/lib/python2.7/site-packages/jmespath/parser.py", line 108, in _parse
    self._tokens = list(self.tokenizer)
  File "/Users/dpopes/scratch/python/virtualenv_run/lib/python2.7/site-packages/jmespath/lexer.py", line 71, in tokenize
    yield {'type': 'number', 'value': int(buff),
ValueError: invalid literal for int() with base 10: '-'
```

Is that behavior by design?

**Comment by danielpops** [comment]
I see that the issue can be worked around by enclosing the term in quotes:

```
>>> jmespath.search('"a-b"', d)
'b-c'
```

I suppose that suggests it's by design?  If so, feel free to close this issue.  Otherwise, please consider fixing and/or updating the documentation to cover this scenario (perhaps this is covered by the extensive grammar documentation, but I couldn't find it)

**Comment by jamesls** [comment]
Sorry for the delayed response.  Yes, this is by design.  There's a `quoted-string` and `unquoted-string` in the grammar rules.  Docs [here](http://jmespath.org/specification.html#identifiers), and a few examples [here](http://jmespath.org/specification.html#examples).

**Comment by Akasurde** [comment]
For posterity, 

localhost.json

```
{
  "msg": {
    "rpc_reply": {
      "interface-information": [
        {
          "physical-interface": [
            {
              "active-alarms": [
                {
                  "interface-alarms": [
                    {
                      "ethernet-alarm-link-down": [
                        {
                          "data": null
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "admin-status": [
                {
                  "attributes": {
                    "junos:format": "Enabled"
                  },
                  "data": "up"
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```

access hyphen key as - 

```python
from jmespath import search
import json
null = None
a = json.load(open("localhost.json", "r"))
print(search('msg.rpc_reply."interface-information"', a))
```

Output is 
```
[{'physical-interface': [{'active-alarms': [{'interface-alarms': [{'ethernet-alarm-link-down': [{'data': None}]}]}]}, {'admin-status': [{'attributes': {'junos:format': 'Enabled'}, 'data': 'up'}]}]}]
```

**Comment by pragyan019** [comment]
I am using jmespath as follows

`data = {
    "value": [
        {
            "datasetId": "cfafbeb1-8037-4d0c-896e-a46fb27ff229",
            "id": "5b218778-e7a5-4d73-8187-f10824047715",
            "name": "SalesMarketing2",
            "webUrl": "https://app.powerbi.com/groups/f089354e-8366-4e18-aea3-4cb4a3a50b48/reports/5b218778-e7a5-4d73-8187-f10824047715",
            "embedUrl": "https://app.powerbi.com/reportEmbed?reportId=5b218778-e7a5-4d73-8187-f10824047715&groupId=f089354e-8366-4e18-aea3-4cb4a3a50b48",
        },
        {
            "datasetId": "cfafbeb1-8037-4d0c-896e-a46fb27ff229",
            "id": "5b218778-e7a5-4d73-8187-f10824047715",
            "name": "SalesMarketing3",
            "webUrl": "https://app.powerbi.com/groups/f089354e-8366-4e18-aea3-4cb4a3a50b48/reports/5b218778-e7a5-4d73-8187-f10824047715",
            "embedUrl": "https://app.powerbi.com/reportEmbed?reportId=5b218778-e7a5-4d73-8187-f10824047715&groupId=f089354e-8366-4e18-aea3-4cb4a3a50b48",
        },
    ]
}`

And setting the jmespath expr dynamically as:
`
report= 'SalesMarketing3'
`
`
jmespath.search(f"'value[?name == {report}]'", data)
`
Instead of getting the dictionary corresponding to "SalesMarketing3", I am getting output as follows, Am I missing something?
>'value[?name == SalesMarketing3]'

Any help is highly appreciated.
