### ISSUE TITLE
Recursive traversal?

### ISSUE THREAD

**Issue by Granitas** [jmespath/jmespath.py#112]
Is it possible to recursively traverse the json tree with jmespath?

for example:

    {
        "one": {
            "two": {
                "three": [{
                    "four": {
                        "name": "four1_name"
                    }
                }, {
                    "four": {
                        "name": "four2_name"
                    }
                }]
            }
        }
    }

Parsing it with something like `..four.name` instead of `one.two.three[].four.name`?
For example how xpath would allow you to `//four/name/text()` instead of `one/two/three/four/name/text()`

Is that possible to do with Jmespath?

**Comment by Granitas** [comment]
Oh this looks like a duplicate of https://github.com/jmespath/jmespath.py/issues/110

**Comment by springcomp** [comment]
@Granitosaurus  We want to [propose this feature to JMESPath](https://github.com/jmespath/jmespath.jep/issues/31) and will include this in the [next iteration for JMESPath Community](https://github.com/jmespath-community/jmespath.spec/discussions/151).
