### ISSUE TITLE
Raise exception when match failure, to distinguish from “matched, value is None”

### ISSUE THREAD

**Issue by benf-wspdigital** [jmespath/jmespath.py#113]
The jmespath.search function returns None in two distinct cases:

```
>>> import jmespath

>>> foo = {'bar': {'lorem': 13, 'ipsum': None}}
>>> repr(jmespath.search('bar.lorem', foo))
'13'
>>> repr(jmespath.search('bar.ipsum', foo))    # Path matches, value None
'None'
>>> repr(jmespath.search('dolor', foo))    # Path does not match
'None'
```

It appears the JMESPath search API returns None in these two distinct cases. How can the caller know the difference between them?

I would expect no return in the case of a match failure, and instead an exception (such as KeyError or ValueError).

**Comment by jamesls** [comment]
If you want to check if a key exists in the hash, you can use the `contains` function:

```
>>> import jmespath
>>> foo = {'bar': {'lorem': 13, 'ipsum': None}}
>>> repr(jmespath.search("bar.ipsum", foo))
'None'
>>> repr(jmespath.search("contains(keys(bar), 'ipsum')", foo))
'True'
```

Let me know if that doesn't work for you.

**Comment by benf-wspdigital** [comment]
The JMESPath specification says, about the value returned for a search:

> The return value for an identifier is the value associated with the identifier. If the identifier does not exist in the JSON document, than a null value is returned.

So if the value associated with the identifier is `null`, the specification deliberately conflates that with the “does not exist” case. Hence this library is behaving correctly by the specification.

I maintain the specification is broken by design. The “does not exist” behaviour should, in order to be easily detected, be entirely disjoint from any valid value that could be returned by a match. Raising an exception would be an appropriate implementation.
