### ISSUE TITLE
0.9.1 date comparisons not working

### ISSUE THREAD

**Issue by goodwinb99** [jmespath/jmespath.py#124]
From https://gitter.im/jmespath/chat:
```
aws ec2 describe-snapshots --owner-id self --query 'Snapshots[?StartTime>='2017--02-01']'
The above command returns and empty set ( '[]' ) when run with v0.9.1, and a list of appropriate snapshots with run with v0.9.0.
```
I have the same problem fetching AMIs by date.  It appears Date comparisons (except ==) are broken in 0.9.1 (and work fine in 0.9.0)

**Comment by jamesls** [comment]
I'll add this behavior back.

What's going on here is that the spec only defines comparisons as valid on numbers (http://jmespath.org/specification.html#ordering-operators).  In 0.9.1, validation was added to enforce this requirement, so things that implicitly worked before now no longer work.

Given this is affecting multiple people I'll add back the support for strings now.  I'll also work on getting the spec updated.

**Comment by AZhyrenkov** [comment]
Hey guys!
I know this is closed, but maybe another issue is connected?
This one: https://github.com/jmespath/jmespath.rb/issues/47
