### ISSUE TITLE
When numbers become LONG search won't match records

### ISSUE THREAD

**Issue by jeffryan** [jmespath/jmespath.py#125]
If data being searched contains numeric values that are large enough to become LONG (depends on sys.maxint of the platform) then jmespath.search can't find them. To illustrate lets consider the following simple query that works:

```
>>> jmespath.search('[?b > `2`]', [{"a": 1, "b": 2}, {"a": 1, "b": 3}])
[{'a': 1, 'b': 3}]

```
Then simply convert the numeric data type of the field being searched to long and note the result is no longer found:

```
>>> jmespath.search('[?b > `2`]', [{"a": 1, "b": 2}, {"a": 1, "b": 3L}])
[]

```

**Comment by jbryan** [comment]
This also occurs when numbers become `Decimal`, something [commonly done when parsing json](http://www.daveoncode.com/2014/10/21/python-reading-numbers-from-json-without-loss-of-precision-using-decimal-class-for-data-processing/) that may have been generated by an implementation with a different float precision than python.  E.g.:

```
>>> jmespath.search('[?b > `2`]', [{"a": 1, "b": 2}, {"a": 1, "b": Decimal(3)}])
[]
```

It seems that to deal with both cases, the change implemented [here](https://github.com/jmespath/jmespath.py/commit/6f2f5834b5df755266ff3f7a5fecb05a019d6da0#diff-e264d131fa420ca3ff588c5a9ce58c75R46) would have been better written to use `Number`:

```
from numbers import Number
def _is_actual_number(x):
     # We need to handle python's quirkiness with booleans,
     # specifically:
     #
     # >>> isinstance(False, int)
     # True
     # >>> isinstance(True, int)
     # True
     if x is True or x is False:
         return False
     return isinstance(x, Number)
```

**Comment by jamesls** [comment]
Fixed via https://github.com/jmespath/jmespath.py/pull/127
