### ISSUE TITLE
jp script has wrong shebang (in jmespath-0.9.2-py2.py3-none-any.whl on pypi)

### ISSUE THREAD

**Issue by mgrandi** [jmespath/jmespath.py#137]
This was previously fixed in this issue: https://github.com/jmespath/jmespath.py/issues/90 , but it seems it has returned. There is a `jp` file in the `jmespath-0.9.2-py2.py3-none-any.whl` wheel that is including a shebang line that looks like it is from the developer's virtualenv (`#!/Users/jamessar/.virtualenvs/a16cce535ca9ee79/bin/python`)

The problem doesn't seem to be the presence of the `jp` command, its just that it has the wrong shebang line. 

Possible solutions:

add a `jp` script (that calls or is the same as `jp.py`, since it seems the current `jp` is different than `jp.py`

or just have setup.py ignore `jp`, or remove whatever is causing this file to be included in builds

workarounds for now:

install `jmespath` by doing `pip3.6 install jmespath --no-use-wheel`

**Comment by jamesls** [comment]
I don't know why that keeps showing up.  I'll get a new release out and ensure that script isn't part of the wheel.  Thanks for reporting.

**Comment by jamesls** [comment]
0.9.3 is out, this should be fixed now.
