### ISSUE TITLE
FR: Implement JMESPath specification for AND and OR operators

### ISSUE THREAD

**Issue by danowar2k** [jmespath/jmespath.py#160]
The specification has && and || operators for expressions defined. It would be nice if those could be provided by this implementation.

**Comment by danowar2k** [comment]
This could also be an issue with the Ansible json_query filter that uses jmespath.py . Is there any place with a sort of checklist which features of the specification are implemented?

**Comment by mjpieters** [comment]
Not sure if this was changed since this ticket was opened, but jmespath.py does implement the boolean `&&` and `||` operators.
