### ISSUE TITLE
Please release a newer version

### ISSUE THREAD

**Issue by RobinRule** [jmespath/jmespath.py#170]
plz release a newer version soon, so that commit: https://github.com/jmespath/jmespath.py/commit/4a521f877596fbd22abad0f9a021c879aa97f900
could be used. This NoneType mapping error is causing lots of troubles

**Comment by hevy-CC4477** [comment]
Is this project dead ?

**Comment by jamesls** [comment]
Noo! Not dead.  There haven't been any new features for a while, but I'd like to start picking things up again.  I'm going through PRs now and I'll get a release out shortly.

**Comment by nateprewitt** [comment]
jmespath 1.0 was released today. Resolving as the referenced commit should be included if it wasn't previously.
