### ISSUE TITLE
Offer to help with the project

### ISSUE THREAD

**Issue by skorokithakis** [jmespath/jmespath.py#173]
I've noticed that activity on this project has slowed, and I was wondering if you needed some help. Would you consider adding the project to [Code Shelter](https://www.codeshelter.co/)? It's an open community of open source maintainers (please feel free to join!) that aims to help OSS projects out (fixing bugs, merging PRs, releasing, etc).

You can [read more details about it](https://www.codeshelter.co/faq/) or [add your project](https://www.codeshelter.co/projects/add/) to it.

**Comment by jamesls** [comment]
Hi, thanks for reaching out.  I would be interested in people that want to help out with the project, but I'd prefer to just add them directly as collaborators to this project.  I'll definitely keep Code Shelter in mind though.  Thanks!
