### ISSUE TITLE
post-finding failed action: maximum of 10 IPv4 addresses

### ISSUE THREAD

**Issue by xgarcias** [jmespath/jmespath.py#177]
Hi,

The finding format in Security Hub defines a maximum of 10 IPv4 addresses in `Resource.Details.AwsEc2Instance.IpV4Addresses` but the resource **ec2** doesn't limit the list in the class **InstanceFinding**

See https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format.html

A dirty workaround is to change the code as below. I ignore if jmespath.search can limit the result:

```
            "IpV4Addresses": jmespath.search(
                "NetworkInterfaces[].PrivateIpAddresses[].PrivateIpAddress", r
            )[0:9]
```

```
FailedFindings': [{'Id': 'eu-central-1/897816849202/61d1691981c34026571dfa7b356f679b/f33f01673d01baefed3cce37deb0b59a', 'ErrorCode': 'InvalidInput', 'ErrorMessage': 'Finding does not adhere to Amazon Finding Format. data.Resources[0].Details.AwsEc2Instance.IpV4Addresses should NOT have more than 10 items'}]
```

**Comment by jamesls** [comment]
Hi, can you clarify what issue you're running into?  Is there something in the jmespath library you'd like us to change?

**Comment by xgarcias** [comment]
Hi,

I am not familiar with jmespath and I am not sure the problem is there. I'd
like to be more helpful but I lack the knowledge.

The Security Hub API limits the number of IP addresses sent in a finding
record  to a maximum of 10 IP addresses and Cloud Custodian is not checking
for this. It simply returns all the public and private IP addresses
attached to an EC2 instance.

Perhaps there's a mechanism already to deal with this.

Kind regards,

Xavier Garcia

**Comment by xgarcias** [comment]
This issue was meant to be open elsewhere.

I don't know how it ended up in jmespath. I apologise the inconvenience.
Please close the issue.
