### ISSUE TITLE
Python 3.8 raises a SyntaxWarning

### ISSUE THREAD

**Issue by mneil** [jmespath/jmespath.py#187]
https://github.com/jmespath/jmespath.py/blob/develop/jmespath/visitor.py#L32

```
SyntaxWarning: "is" with a literal. Did you mean "=="?  if x is 0 or x is 1:
if x is 0 or x is 1:
```

I noticed this error when installing boto3 (requires jmespath 0.9.4) with Python 3.8. The warning was not present in Python 3.7.x

Lines 32, 34, 260 are affected.

**Comment by uncledru** [comment]
When this is running in an AWS Lambda function -- it's putting an extra 10 lines of logs into CloudWatch (which costs money). Does anyone have an interim workaround until this gets fixed?

**Comment by jnalley** [comment]
@uncledru you can set `PYTHONWARNINGS=ignore` as an environment variable in your lambda to disable ALL warnings.

You can disable `SyntaxWarning` in your code using:

```
import warnings
warnings.filterwarnings("ignore", category=SyntaxWarning)
```

**Comment by Qu4tro** [comment]
If anyone wants to disable `SyntaxWarning` only for jmespath.visitor:
```
warnings.filterwarnings(
    action='ignore',
    category=SyntaxWarning,
    module=r'jmespath\.vistor'
)
```

**Comment by sanddevil** [comment]
To all of us who copy and paste -
Beware of the typo in visitor in the code snippet above :D

**Comment by Qu4tro** [comment]
Thanks for the heads up! Updated.
