### ISSUE TITLE
Problems installing jmespath in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Tomasthanes** [jmespath/jmespath.py#201]
I'm running Ubuntu 20.04 LTS in a VirtualBox VM and I just tried to install ansible with the following command line:

`sudo apt-get install ansible -y`

One of the dependencies that it installed was jmespath and I saw the following output from apt-get:

> Setting up python3-jmespath (0.9.4-2) ...
> /usr/lib/python3/dist-packages/jmespath/visitor.py:32: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if x is 0 or x is 1:
> /usr/lib/python3/dist-packages/jmespath/visitor.py:32: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if x is 0 or x is 1:
> /usr/lib/python3/dist-packages/jmespath/visitor.py:34: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   elif y is 0 or y is 1:
> /usr/lib/python3/dist-packages/jmespath/visitor.py:34: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   elif y is 0 or y is 1:
> /usr/lib/python3/dist-packages/jmespath/visitor.py:260: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if original_result is 0:

I'm guessing that this is not the result you expected.  Is there any additional information that I can provide you?

I've attached a text file with all of the apt-get output.
[apt-get output.txt](https://github.com/jmespath/jmespath.py/files/4560388/apt-get.output.txt)

**Comment by stuartatmicrosoft** [comment]
Switching the above code references to == instead of "is" remediates this.

**Comment by Tomasthanes** [comment]
Is this something that the tens of thousands of package installers are supposed to do or would you do this in the next release of the package?

**Comment by jamesls** [comment]
Fixed via https://github.com/jmespath/jmespath.py/issues/187 but not released (only in develop right now).  I'll get a release out either today or Monday.

**Comment by Tomasthanes** [comment]
Thank you for the quick response!

**Comment by vielmetti** [comment]
Reported upstream to Ubuntu as

https://bugs.launchpad.net/ubuntu/+source/ansible/+bug/1877792
