### ISSUE TITLE
Python 2.7 deprecation plan?

### ISSUE THREAD

**Issue by bsolomon1124** [jmespath/jmespath.py#215]
Related to https://github.com/jmespath/jmespath.py/pull/166 and https://github.com/jmespath/jmespath.py/pull/175, is there a deprecation timeline for all of Python 2, or does jmespath plan to support Python 2.7 indefinitely?

It looks like the current version is 0.10.0. Having the information available, for instance "Version 1.x will drop support for Python 2" would help downstream projects that want to dually support Python 2 and 3 pin jmespath<1.

**Comment by jamesls** [comment]
I'll put together a plan, but I'm thinking 1.0 will deprecate 2.7 as well as older versions of python3 (probably up to either 3.6 or 3.7).

I'm thinking a 1.0 release in Jan maybe, depending on feedback.

**Comment by jamesls** [comment]
Consolidating python version deprecations to tracking issue https://github.com/jmespath/jmespath.py/issues/268
