### ISSUE TITLE
Suggestion: drop support for Python 3.3

### ISSUE THREAD

**Issue by simonw** [jmespath/jmespath.py#218]
The tests failed on Python 3.3 for #217 with this error:

> ERROR: You need Python 2.7 or 3.4+ to install the typing package.

I'm not sure what depends on `typing` but since Python 3.3 reached end-of-life on 2017-09-29 (according to https://www.python.org/dev/peps/pep-0398/#lifespan) I think it's safe to drop support entirely.

**Comment by jamesls** [comment]
Consolidating python version deprecations to tracking issue https://github.com/jmespath/jmespath.py/issues/268
