### ISSUE TITLE
Officially support Python 3.8, 3.9, 3.10 on PyPI

### ISSUE THREAD

**Issue by uri-rodberg** [jmespath/jmespath.py#265]
PyPi only lists support of `jmespath` to Python <= 3.7. I would like to see `jmespath` officially supporting newer versions - Python 3.8, 3.9, 3.10.

From my testing, `jmespath==0.10.0` works with Python 3.8, 3.9, 3.10.

**Comment by hugovk** [comment]
Please see PR https://github.com/jmespath/jmespath.py/pull/266.

**Comment by nateprewitt** [comment]
Hi @uri-rodberg, 1.0 was released to PyPI today adding classifiers for 3.8 and 3.9. Unfortunately, #266 was missed prior to release but it will be added with the next release.
