### ISSUE TITLE
can jmespath support parse json-key with chinese like the next example

### ISSUE THREAD

**Issue by pandatools** [jmespath/jmespath.py#306]
import jmespath
data = {"姓名": "张三", "年龄": 18, "性别": "男"}
query = '姓名'
result = jmespath.search(query, data)

**Comment by jamesls** [comment]
Yes, you'll need to surround the key name in double quotes (i.e a [quoted identifier](https://jmespath.org/specification.html#identifiers)):

```
import jmespath
data = {"姓名": "张三", "年龄": 18, "性别": "男"}
query = '"姓名"'
result = jmespath.search(query, data)
print(result)
```
prints:
```
张三
```
