### ISSUE TITLE
Filter projection when key starts with @

### ISSUE THREAD

**Issue by rennerocha** [jmespath/jmespath.py#325]
I am parsing a JSON-LD content returned by a proeduct page of a marketplace. I am tryionh to use a [filter projection](https://jmespath.org/tutorial.html#filter-projections) to return data of specific types. However, the key that I want to search starts with `@`, and the search is not working correctly.

If this a bug or I am doing something wrong when defining the JMESPath for the data I want?

For example, given the following:

```
data = [
    {
        '@context': 'https://schema.org',
        'type': 'WebSite',
        'name': 'Marketplace'
    },
    {
        '@context': 'https://schema.org',
        'type': 'Product',
        'name': 'Product Name'
    }
]
```

`jmespath.search("[?type=='Product'].name", data)` returns `Product Name` (as expected)

But for this input (which is the one that I am trying to parse):

```
data = [
    {
        '@context': 'https://schema.org',
        '@type': 'WebSite',
        'name': 'Marketplace'
    },
    {
        '@context': 'https://schema.org',
        '@type': 'Product',
        'name': 'Product Name'
    }
]
```

I can´t use `jmespath.search("[?@type=='Product'].name", data)` or any variation of it.

**Comment by ftnt-dspille** [comment]
@rennerocha  Anytime you see special characters in a json key, just know you'll need to put the key in double quotes. Try 

```python
jmespath.search('[?"@type" == `Product`].name', data)
```

This also works 

```python
jmespath.search("[?\"@type\" == 'Product'].name", data)
```

**Comment by rennerocha** [comment]
Thanks @ftnt-dspille !
I didn't tried to use ` , so it wasn't working! Now I get the data that I want!
