### ISSUE TITLE
Added "current index" support for projections

### ISSUE THREAD

**Issue by mtdowling** [jmespath/jmespath.py#61]
It is sometimes useful when in a projection to be able to know which element of the thing being projected you are evaluating. When projecting on an array, the index would be the current index of the array (starting at 0), and when projecting an object, the index would be the current key of the array. I would suggest adding a new token to the grammar to represent the "current_node". The character I would suggest is `#`.

I can flesh this out with more details and a JEP if there's interest in something like this.

**Comment by mtdowling** [comment]
I think that instead of "current index" we should think about adding support for turning collections into lists of tuples (key, value). Closing this issue.

**Comment by brucellino** [comment]
Hi there!
I need to slice an array in JSON, but by excluding elements in it. I had thought about doing this with something similar to [the previous comment](https://github.com/jmespath/jmespath.py/issues/61#issuecomment-50593380), but it seems this is not happening.
