### ISSUE TITLE
OR (`||`) behaviour seems odd

### ISSUE THREAD

**Issue by jonathanj** [jmespath/jmespath.py#83]
From <http://jmespath.org/specification.html#or-expressions>:

> An or expression will evaluate to either the left expression or the right expression. If the evaluation of the left expression is not false it is used as the return value. If the evaluation of the right expression is not false it is used as the return value. If neither the left or right expression are non-null, then a value of null is returned. A false value corresponds to any of the following conditions:
> * False boolean: ``false``

```python
search('a == `foo`', {"a": "foo", "b": "bar"})  # => True
search('b == `bar`', {"a": "foo", "b": "bar"})  # => True
search('a == `foo` || b == `bar`', {"a": "foo", "b": "bar"})  # => False
```

I would have expected a `True` value for all three expressions.

**Comment by jamesls** [comment]
You're correct, these should be `True`.  The parsing precedence is off here.  I'll get this updated.

**Comment by jamesls** [comment]
Fixed via: https://github.com/jmespath/jmespath.py/pull/96

That PR also adds general support for boolean operations, ors, ands, and nots.
