### ISSUE TITLE
Minus (-) char in expression raises LexerError exception

### ISSUE THREAD

**Issue by Kenuat** [jmespath/jmespath.py#87]
Hi, if path contains minus character, the following error raises:
```
jmespath.exceptions.LexerError: Bad jmespath expression: Unknown character:
statistics.destinations-voice
                       ^
```

**Comment by jamesls** [comment]
If a key name has anything besides `[_a-zA-Z908]`, it needs to be quoted, so this should work for you:

`statistics."destinations-voice"`
