### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '-'

### ISSUE THREAD

**Issue by skwashd** [jmespath/jmespath.py#98]
Running 0.9.0 I am getting "ValueError: invalid literal for int() with base 10: '-'" errors when trying the following:

JSON
```json
{
    "minimum-stability": "dev",
    "prefer-stable": true,
}
```

Code
```python
result = jmespath.search('prefer-stable', composer_json)
```

Stack Trace
```
Traceback (most recent call last):
  File "./validate.py", line 98, in <module>
    result = jmespath.search('prefer-stable', composer_json)
  File "/Users/dave/.virtualenvs/composer-validator/lib/python2.7/site-packages/jmespath/__init__.py", line 12, in search
    return parser.Parser().parse(expression).search(data, options=options)
  File "/Users/dave/.virtualenvs/composer-validator/lib/python2.7/site-packages/jmespath/parser.py", line 87, in parse
    parsed_result = self._do_parse(expression)
  File "/Users/dave/.virtualenvs/composer-validator/lib/python2.7/site-packages/jmespath/parser.py", line 95, in _do_parse
    return self._parse(expression)
  File "/Users/dave/.virtualenvs/composer-validator/lib/python2.7/site-packages/jmespath/parser.py", line 108, in _parse
    self._tokens = list(self.tokenizer)
  File "/Users/dave/.virtualenvs/composer-validator/lib/python2.7/site-packages/jmespath/lexer.py", line 71, in tokenize
    yield {'type': 'number', 'value': int(buff),
ValueError: invalid literal for int() with base 10: '-'
```

The JSON above is a snippet from a composer.json file.  It passes jsonlint and works with the [jmespath tutorial](http://jmespath.org/tutorial.html).

Let me know if you need any more info.

**Comment by jamesls** [comment]
Looks like a regression in the error message.  In 0.6.2 you get error message:

```
jmespath.exceptions.LexerError: Bad jmespath expression: Unknown character:
prefer-stable
      ^
```

Per the [spec](http://jmespath.org/specification.html#identifiers), identifiers are defined as:

```
identifier        = unquoted-string / quoted-string
unquoted-string   = (%x41-5A / %x61-7A / %x5F) *(  ; A-Za-z_
                        %x30-39  /  ; 0-9
                        %x41-5A /  ; A-Z
                        %x5F    /  ; _
                        %x61-7A)   ; a-z
```

so it needs to match `[A-Za-z_][0-9A-Z_a-z]*`.  For a key with a hyphen, you'll need to use a `quoted-string`, the expression should be:

```
>>> jmespath.search('"prefer-stable"', d)
```

Looks like the JMESPath tutorial actually has a bug that allows this character when it shouldn't.

That being said, I *think* we might be able to relax the constraint on unquoted identifiers to support this, but I'll need to do some digging to ensure this is an ok change.

In the meantime, you'll have to quote any key names that have chars beside `[A-Za-z0-9_]`.

cc @mtdowling

**Comment by skwashd** [comment]
@jamesls thanks for the clarification and lexer fix.
